
name: Add hostnames to Akamai AppSec policy
on:
  workflow_dispatch:

env:
  EDGERC: ${{ secrets.AKAMAI_EDGERC  }}

jobs:
  build:
    name: Manage hostname list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4       
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run update hostnames for AppSec
        run: go run -v . 
      
      - name: Env list
        run: env
